name: Build new Docker image

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/pogo-data-viewer:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME